name: Publish NPM Package

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: "NPM authentication token"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Verify tag matches package.json version
        run: |
          # Extract tag name
          TAG_VERSION=${GITHUB_REF#refs/tags/}

          # Get version from package.json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          echo "Tag version: $TAG_VERSION"
          echo "Package.json version: $PACKAGE_VERSION"

          # Check if versions match
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
