name: Docker GHCR Build and Push (Node.js)

on:
  workflow_call:
    inputs:
      app-name:
        description: "Name of the Node.js package"
        required: true
        type: string
      node-version:
        description: "Node.js version to use"
        required: false
        default: "20.x"
        type: string
      dockerfile-path:
        description: "Dockerfile to use"
        required: false
        default: "Dockerfile"
        type: string
      build-args:
        description: "Additional build arguments to pass to Docker build"
        required: false
        type: string
        default: ""
      local-test:
        description: "Set to true when running locally with act"
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}/${{ inputs.app-name }}

jobs:
  build:
    name: build and push (node-${{ inputs.node-version }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: ${{ !inputs.local-test && github.event_name != 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{version}}
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ !inputs.local-test && github.event_name != 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          context: .
          file: ${{ inputs.dockerfile-path }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            NODE_VERSION=${{ inputs.node-version }}
            ${{ inputs.build-args }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
