# Publishes the Docker image.

name: Docker GHCR Build and Push

on:
  workflow_call:
    inputs:
      rust-binary-name:
        description: 'Name of the binary to build'
        required: true
        type: string
      rust-channel:
        description: 'Rust channel to use (stable, beta, nightly, or specific version like 1.70.0)'
        required: false
        default: 'stable'
        type: string
      requires-private-deps:
        description: 'Requires private dependencies to be fetched, sets up ssh-agent'
        required: false
        default: false
        type: boolean
      dockerfile-path:
        description: 'Dockerfile to use'
        required: false
        default: 'Dockerfile'
        type: string
      build-flags:
        description: 'Build flags to pass to cargo'
        required: false
        type: string
        default: ''
      require-lockfile:
        description: 'Require a Cargo.lock file to be present (--locked)'
        required: false
        default: false
        type: boolean
    secrets:
      SSH_PRIVATE_KEY:
        description: 'SSH private key for fetching private dependencies'
        required: false

env:
  CARGO_TERM_COLOR: always
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}/${{ inputs.rust-binary-name }}

jobs:
  build:
    name: Bulid & Push (${{ inputs.rust-channel }})
    runs-on: 
      group: ${{ matrix.runner }}
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: big-bois-x86
          - arch: arm64
            platform: linux/arm64
            runner: big-bois-aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust-channel }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ inputs.rust-channel }}-docker-${{ matrix.arch }}-${{ inputs.require-lockfile }}
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.arch }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup ssh-agent
        id: ssh-agent
        if: ${{ inputs.requires-private-deps == true }}
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        if: ${{ inputs.requires-private-deps == false }}
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          context: .
          file: ${{ inputs.dockerfile-path }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          build-args: |
            RUST_TOOLCHAIN=${{ inputs.rust-channel }}
            BUILD_FLAGS=${{ inputs.build-flags }} ${{ inputs.require-lockfile == true && '--locked' || '' }}
      - name: Build and push
        if: ${{ inputs.requires-private-deps == true }}
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          platforms: ${{ matrix.platform }}
          context: .
          file: ${{ inputs.dockerfile-path }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          ssh: default
          build-args: |
            RUST_TOOLCHAIN=${{ inputs.rust-channel }}
            BUILD_FLAGS=${{ inputs.build-flags }} ${{ inputs.require-lockfile == true && '--locked' || '' }}
        env: 
          CARGO_NET_GIT_FETCH_WITH_CLI: true
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Export digest
        run: |
          echo "digest-${{ matrix.arch }}=$(docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ github.sha }} --format '{{.Manifest.Digest}}' | cut -d: -f2)" >> $GITHUB_OUTPUT
    outputs:
      digest-amd64: ${{ steps.export-digest.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.export-digest.outputs.digest-arm64 }}
  publish-manifest-list:
    name: Publish Docker manifest list
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{version}}
            type=sha,format=short
      - name: Create and push manifest list
        run: |
          docker buildx imagetools create \
            $(echo "${{ steps.meta.outputs.tags }}" | jq -r '.[]' | xargs -I {} echo "-t {}") \
            ${{ env.REGISTRY_IMAGE }}@sha256:${{ needs.build.outputs.digest-amd64 }} \
            ${{ env.REGISTRY_IMAGE }}@sha256:${{ needs.build.outputs.digest-arm64 }}